<?php

namespace App\Services;

use App\Models\Clearance;
use App\Services\Pdf\SimplePdfDocument;
use Illuminate\Support\Facades\Storage;

class ClearancePdfService
{
    public function generate(Clearance $clearance): string
    {
        $clearance->loadMissing('steps.officeDesignation');

        $pdf = new SimplePdfDocument();
        $y = 752;

        $hasLogo = $pdf->jpegImage(public_path('images/lnu-logo-pdf.jpg'), 48, 704, 54, 54)
            || $pdf->pngImage(public_path('images/lnu-logo.png'), 48, 704, 54, 54);
        $headerX = $hasLogo ? 116 : 48;

        $pdf->text($headerX, $y, 'LEYTE NORMAL UNIVERSITY', 18, true);
        $y -= 24;
        $pdf->text($headerX, $y, 'GENERAL STUDENTS CLEARANCE', 13, true);
        $y -= 26;

        $pdf->text(48, $y, 'Student Name:', 10, true);
        $pdf->text(140, $y, $clearance->student_name, 10);

        $pdf->text(365, $y, 'Student ID:', 10, true);
        $pdf->text(445, $y, $clearance->student_id_number, 10);

        $y -= 18;

        $pdf->text(48, $y, 'Program:', 10, true);
        $programText = $clearance->program_code . ' - ' . $clearance->program_name;
        $programEndY = $pdf->wrappedText(110, $y, 210, $programText, 10);
        $pdf->text(365, $y, 'Year Level:', 10, true);
        $pdf->text(445, $y, $this->yearLevelLabel($clearance->year_level), 10);
        $y = min($programEndY, $y - 18);
        $y -= 4;

        $pdf->text(48, $y, 'Semester:', 10, true);
        $pdf->text(140, $y, $clearance->semester_label, 10);

        $pdf->text(365, $y, 'Reference No.:', 10, true);
        $pdf->text(445, $y, $clearance->reference_number ?? 'Pending', 10);

        $y -= 28;

        $statement = 'This certifies that the student named above has completed all required clearance approvals for the indicated semester.';
        $y = $pdf->wrappedText(48, $y, 520, $statement, 11);
        $y -= 14;

        $pdf->line(48, $y, 564, $y);
        $y -= 18;

        $pdf->text(48, $y, 'Signed Office', 10, true);
        $pdf->text(365, $y, 'Approved At', 10, true);
        $y -= 10;
        $pdf->line(48, $y, 564, $y);
        $y -= 18;

        foreach ($clearance->steps->where('status', 'approved') as $step) {
            $pdf->wrappedText(48, $y, 280, $step->office_label, 10);
            $pdf->wrappedText(
                365,
                $y,
                190,
                $this->formatDateTime($step->signed_at),
                10
            );

            $y -= 22;
        }

        $y -= 12;
        $pdf->line(48, $y, 564, $y);
        $y -= 22;

        $footer = 'Generated by the Student Clearance System. Keep this PDF and transaction reference for verification.';
        $pdf->wrappedText(48, $y, 520, $footer, 9);

        $path = 'clearances/' . strtolower($clearance->reference_number ?? ('clearance-' . $clearance->id)) . '.pdf';
        Storage::disk('local')->put($path, $pdf->output());

        return $path;
    }

    protected function yearLevelLabel(int $yearLevel): string
    {
        return match ($yearLevel) {
            1 => '1st Year',
            2 => '2nd Year',
            3 => '3rd Year',
            4 => '4th Year',
            default => $yearLevel . 'th Year',
        };
    }

    protected function formatDateTime($value): string
    {
        if ($value === null) {
            return 'Pending';
        }

        return $value
            ->copy()
            ->timezone('Asia/Manila')
            ->format('M d, Y h:i A');
    }
}
